trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  inputs:
    Contents: 'azuredeploy*'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: AzureCLI@2  
  displayName: 'build bicep artifact' 
  inputs: 
    azureSubscription: 'rg-dev' 
    scriptType: 'pscore'  
    scriptLocation: 'inlineScript'  
    inlineScript: 'az bicep build --file core.bicep'

- task: CopyFiles@2
  inputs:
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'